### ISSUE TITLE
installer for Formiko (.bat to .exe on Windows)

### ISSUE THREAD

**Issue by HydrolienF** [HydrolienF/Formiko#98]
Empaqueter le fichier en .exe pour windows.
Idéalement le jeu vas s'installer dans "C:\Program Files" et crée un raccourci sur le bureau.

**Comment by Jerryh2-0** [comment]
Demander avant de faire un raccourci sur le bureau*

**Comment by HydrolienF** [comment]
faire un installateur Formiko légé qui détecte l'OS et propose d'installer la dernière version sable ou la dernière version (+ java.exe et le répertoire générer par jlink)
puis qui unzip les fichiers avec unzip (potentiellement installer sur linux) ou la commande PowerShell).
Ca permet de faire valider l'OS et la langue par l'utilisateur & de stocker 1 seul fois les 3 jlinks.

**Comment by HydrolienF** [comment]
Installer can be create with jpackage for every OS

The cmd that I use for Windows. It work well but data can't be edit from there without admin perm.

jpackage --input in -d out --name Formiko --main-jar Formiko.jar --main-class fr.formiko.formiko.Main --app-version 1.32.4 --description "Formiko, a game about ant." --icon icon.ico --resource-dir in/data --win-shortcut --win-dir-chooser --win-menu --win-console

**Comment by HydrolienF** [comment]
It allow to install & unistall Formiko with 2 clics only & create a shortcut to the desctop.

**Comment by HydrolienF** [comment]
Impact_t#2548 suggest to use 
```System.getProperty("user.home");```
to have a place were to move the /data/ (in Formiko/data/ for example).

**Comment by HydrolienF** [comment]
Use appData file will be a better idea for Windows

**Comment by HydrolienF** [comment]
Installer currently do 33 Mb, we will consider that it is good. Only big data file will not be add in the installer but download during the game #193

**Comment by HydrolienF** [comment]
To have data file to an other directory we can download the last compatible version of the data to this directory.
It will smaler the installer a bit.
We only need to update data & version var in .java file if we make an update for data.

**Comment by HydrolienF** [comment]
Finaly it will be a .msi.

**Comment by HydrolienF** [comment]
It have been add to github action
